name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3      
    - name: Build
      run: cd frontend ; npm install react ; npm run build ; cd ..
    - name: Package
      run: ./package.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /tmp/hifistreamer-app-*.tar.gz
