name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        uses: ./.github/workflows/build.yml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            frontend/www
