name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3      
    - name: Run build
      run: cd frontend ; npm install react ; npm run build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          hifistreamer-app/www
